### ISSUE TITLE
hard coded file, strange usage

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITKSpellChecking#13]
This [line in codespell.py](https://github.com/SimpleITK/SimpleITKSpellChecking/blob/ddee26f4b2ec37ebb7300534ed2927d904503ac6/codespell.py#L17)  does not make sense, hard coding the path to a file on a specific user's directory structure. This path is later used [here](https://github.com/SimpleITK/SimpleITKSpellChecking/blob/ddee26f4b2ec37ebb7300534ed2927d904503ac6/codespell.py#L221-L225), what is the motivation for this? If the input list is empty, just return with exit 0, success.

**Comment by dave3d** [comment]
Yeah, that's legacy junk from when I first wrote it.  I didn't feel like typing in the whole command line every time I ran it.
I'll get rid of it.

**Comment by dave3d** [comment]
https://github.com/SimpleITK/SimpleITKSpellChecking/pull/14
