### ISSUE TITLE
restructure the repository and add testing

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITKSpellChecking#8]
First step towards a nice Python package, via the [PR](https://github.com/SimpleITK/SimpleITKSpellChecking/pull/7) from @blowekamp.

Complete the process and create the directory structure which is commonly used for Python packages, see [packaging tutorial](https://github.com/SimpleITK/SimpleITKSpellChecking/blob/cd73a026dc093e60b66aa6862ef651acdd30e4a8/utils/myspell.py#L26).

Also, add testing and a bit of cleanup (e.g. [here](https://github.com/SimpleITK/SimpleITKSpellChecking/blob/cd73a026dc093e60b66aa6862ef651acdd30e4a8/utils/myspell.py#L25-L26)).

**Comment by blowekamp** [comment]
The configuration of the pyproject.toml is complete. It is written so support a single installed python executable in the python packaging system.

**Comment by jcfr** [comment]
@blowekamp @dave3d I think this can be closed as well.

Testing was introduced in the following pull requests:
* https://github.com/SimpleITK/SimpleITKSpellChecking/pull/11
* https://github.com/SimpleITK/SimpleITKSpellChecking/pull/12

Packaging support was introduced in this pull request:
* https://github.com/SimpleITK/SimpleITKSpellChecking/pull/7
